export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Home } from './Home'
export { default as Journey } from './Journey'
export { default as Navbar } from './Navbar'
export { default as Projects } from './Projects'